### ISSUE TITLE
Formatting error for `uuid` columns

### ISSUE THREAD

**Issue by anupghogare** [altaurog/pgcopy#45]
Facing `Value Error` while formatting `uuid` columns.

**ValueError: error formatting value 3bb8c98d-6cb0-4c2c-9cef-7a702cb63268 for column uuid**

**Comment by altaurog** [comment]
Are you passing a `str` or a `uuid.UUID` instance?  You must pass the latter.  The behavior you describe is expected if you pass it a `str`.

**Comment by anupghogare** [comment]
I'm not explicitly passing the `str`, below is the code snippet. 

```
table = 'public.abc'
columns = ('name', 'cmetadata', 'uuid') 

src_cur.execute(f"""

select * from {table}

""")

results = src_cur.fetchall()

mgr = CopyManager(dest_conn, table, columns)
mgr.copy(results)
dest_conn.commit()
```
However I think we need to safeguard the type conversion against the input string something like below -

```
def uuid_formatter(guid):
    guid = uuid.UUID(guid)
    return "i2Q", (16, (guid.int >> 64) & MAX_INT64, guid.int & MAX_INT64)

**Comment by altaurog** [comment]
Some db adapters will convert `uuid` values from the db to `uuid.UUID`, but apparently yours doesn’t.  Ensuring the correct data input is part of the contract the pgcopy api exposes, and it is an easy one to meet.  We can’t just blindly wrap the input in a call to `uuid.UUID()`, because if it _is_ a UUID instance, it will fail:
```
>>> uuid.UUID(uuid.uuid4())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/uuid.py", line 174, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'UUID' object has no attribute 'replace'
```
Similarly, I don’t think there is a compelling reason to add conditional logic here.
